movie-project/app/home/forms.py
# coding:utf8
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField,StringField,PasswordField,FileField,TextAreaField
from wtforms.validators import DataRequired,EqualTo,Email,Regexp,ValidationError
from app.modules import User

class RegisterForm(FlaskForm):
    """会员注册表单"""
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称")
        ],
        description="昵称",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入昵称！",
            # "required": 'required'
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
            # "required": 'required'
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机号"),
            Regexp("1[3458]\d{9}",message="手机格式不正确")
        ],
        description="手机",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号！"
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码")
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入密码！"
        }
    )
    repwd = PasswordField(
        label="请再次输入密码",
        validators=[
            DataRequired("请再次输入密码"),
            EqualTo('pwd','两次输入密码不一致')
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请再次输入密码！"
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-primary btn-block btn-flat"
        }
    )

    def validate_name(self,field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError("昵称已存在")

    def validate_email(self,field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已存在")

    def validate_phone(self,field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError("手机号已存在")

class LoginForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号")
        ],
        description="账号",
        render_kw={
            "class": "form-control import-lg",
            "placeholder": "请输入账号！"
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码")
        ],
        description="密码",
        render_kw={
            "class": "form-control import-lg",
            "placeholder": "请输入密码！"
        }
    )
    submit = SubmitField(
        '登陆',
        render_kw={
            "class": "btn btn-primary btn-block btn-flat"
        }
    )

class UserDetailForm(FlaskForm):
    name = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号")
        ],
        description="账号",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入账号！"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
            # "required": 'required'
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机号"),
            Regexp("1[3458]\d{9}", message="手机格式不正确")
        ],
        description="手机",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号！"
        }
    )
    face = FileField(
        label="头像",
        validators=[
            DataRequired("上传头像！")
        ],
        description="上传头像"
    )
    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介！")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "row": "10!"
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            "class": "btn btn-success"
        }
    )

class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码！")
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入旧密码!",
        }
    )
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码！")
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码!",
        }
    )
    submit = SubmitField(
        "修改密码",
        render_kw={
            "class": "btn btn-success"
        }
    )

    def validate_old_pwd(self, field):
        from flask import session
        pwd = field.data
        name = session["user"]
        user = User.query.filter_by(name=name).first()
        if not user.check_pwd(pwd):
            raise ValidationError("旧密码错误！")

movie-project/app/home/__init__.py
# coding:utf8
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

movie-project/app/home/views.py
# coding:utf8
from . import home
from flask import render_template, url_for, redirect, flash, session, request, abort
from flask import render_template, redirect, url_for
from app.home.forms import RegisterForm, LoginForm,UserDetailForm,PwdForm
from app.modules import User, UserLog,Preview,Tag
from app import app, db
from functools import wraps
from werkzeug.utils import secure_filename
import uuid,os,datetime


# 装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "user" not in session:
            return redirect(url_for("home.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function

def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime('%Y%m%d%H%M%S') + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


# 登陆页面
@home.route("/login/", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data["name"]).first()
        if not user.check_pwd(data["pwd"]):
            flash("密码错误", 'err')
            return redirect(url_for("home.login"))
        session["user"] = user.name
        session["user_id"] = user.id
        userlog = UserLog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for("home.user"))
    return render_template("home/login.html", form=form)


@home.route("/logout/")
def logout():
    session.pop("user", None)
    session.pop("user_id", None)
    return redirect(url_for("home.login"))  # 注册


@home.route("/register/", methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    from werkzeug.security import generate_password_hash
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data["name"],
            pwd=generate_password_hash(data["pwd"]),
            email=data["email"],
            phone=data["phone"],
            uuid=uuid.uuid4().hex
        )
        db.session().add(user)
        db.session.commit()
        flash("注册会员成功", 'ok')
    return render_template("home/register.html", form=form)


# 会员中心
@home.route("/user/",methods=['GET','POST'])
@user_login_req
def user():
    form = UserDetailForm()
    user = User.query.get(int(session["user_id"]))
    form.face.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        file_face = secure_filename(form.face.data.filename)
        if not os.path.exists(app.config["FC_DIR"]):
            os.makedirs(app.config["FC_DIR"])
            os.chmod(app.config["FC_DIR"], "rw")
        user.face = change_filename(file_face)
        form.face.data.save(app.config["FC_DIR"] + user.face)
        name_count = User.query.filter_by(name=data["name"]).count()
        if data["name"] != user.name and name_count == 1:
            flash("昵称已存在！","err")
            return redirect(url_for())
        email_count = User.query.filter_by(email=data["email"]).count()
        if data["email"] != user.email and email_count == 1:
            flash("昵称已存在！", "err")
            return redirect(url_for())
        phone_count = User.query.filter_by(phone=data["phone"]).count()
        if data["phone"] != user.phone and phone_count == 1:
            flash("昵称已存在！", "err")
            return redirect(url_for())
        user.name = data["name"]
        user.phone = data["phone"]
        user.email = data["email"]
        user.info = data["info"]
        db.session.add(user)
        db.session.commit()
        flash("修改会员信息成功！", "ok")
        return redirect(url_for("home.user"))
    return render_template("home/user.html",form=form,user=user)


# 修改密码
@home.route("/pwd/", methods=['GET','POST'])
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session["user"]).first()
        if not user.check_pwd(data["old_pwd"]):
            flash("旧密码错误",'err')
            return redirect(url_for("user.pwd"))
        from werkzeug.security import generate_password_hash
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash("修改密码成功！请重新登陆", "ok")
        return redirect(url_for("home.logout"))
    return render_template("home/pwd.html",form=form)


# 评论
@home.route("/comments/")
def comments():
    return render_template("home/comments.html")


# 会员日志列表
@home.route("/loginlog/list/<int:page>", methods=['GET'])
def userloginlog_list(page=None):
    if page is None:
        page = 1
    page_data = UserLog.query.order_by(
        UserLog.addtime.desc()
    ).paginate(page=page, per_page=10)
    return render_template("home/loginlog.html",page_data=page_data)


# 电影收藏
@home.route("/moviecol/")
@user_login_req
def moviecol():
    return render_template("home/moviecol.html")


@home.route("/")
def index():
    tag = Tag.query.all()
    tid = request.args.get("tid",0)
    star = request.args.get("star",0)
    time = request.args.get("time",0)
    pm = request.args.get("pm",0)
    cm = request.args.get("cm",0)
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=pm
    )
    return render_template("home/index.html ",tag = tag,p=p)


# 动画
@home.route("/animation/")
def animation():
    data = Preview.query.all()
    return render_template("home/animation.html",data=data)


# 搜索
@home.route("/search/")
def search():
    return render_template("home/search.html")


# 播放
@home.route("/play/")
def play():
    return render_template("home/play.html")

movie-project/app/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热映电影</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='anim/css/style.css')}}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
	<div class="main_banner_wrap">
		<canvas id="myCanvas" width="150" height="150"></canvas>
		<div class="main_banner_box" id="m_box">
			<a href="javascript:void(0)" class="banner_btn js_pre">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<a href="javascript:void(0)" class="banner_btn btn_next js_next">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<ul>
				{% for v in data%}
				<li id="{{v.id}}">
					<a href=""><span style="opacity:0;"></span></a>
					<img src="{{url_for('static', filename='uploads/'+v.logo)}}" alt="">
					<p style="bottom:0">{{v.title}}</p>
				</li>
				{%endfor%}
			</ul>
			<!--火狐倒影图层-->
			<p id="rflt"></p>
			<!--火狐倒影图层-->
		</div>
		<!--序列号按钮-->
		<div class="btn_list">
			<span class="curr"></span><span></span><span></span><span></span><span></span>
		</div>
	</div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{url_for('static', filename='anim/js/jquery.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='anim/js/jquery.js')}}"></script>

</body>
</html>

movie-project/app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
           .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css%}

    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index')}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static',filename='base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="{{url_for('home.search')}}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="user.html"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
   {% block content %} {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.rule.com&nbsp;沪ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static',filename='base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/wow.min.js')}}"></script>
<script src="{{url_for('static',filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
{% block js%}{% endblock %}
</body>
</html>

movie-project/app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
           .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css%}

    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index')}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static',filename='base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="{{url_for('home.search')}}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="user.html"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{%block content%} {%endblock%}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.rule.com&nbsp;沪ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static',filename='base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{url_for('static',filename='base/js/wow.min.js')}}"></script>
<script src="{{url_for('static',filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
{% block js%}{% endblock %}
</body>
</html>

movie-project/app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="md1" href="{{url_for('home.user')}}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="md2" href="{{url_for('home.pwd')}}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="md3" href="{{url_for('home.comments')}}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="md4" href="{{url_for('home.userloginlog_list',page=1)}}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="md5" href="{{url_for('home.moviecol')}}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>

movie-project/app/templates/home/moviecol.html
{% extends "home/home.html" %}
{% block css %}
<style>
    .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
        padding-right: 3px;
        padding-left: 3px;
    }
</style>
{% endblock %}
{% block content %}
{% include "home/menu.html" %}

<div class="col-md-9">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
        </div>
        <div class="panel-body">
            <div class="col-md-12">
                {% for in v range(1,10)%}
                <div class="media">
                    <div class="media-left">
                        <a href="{{url_for('home.play')}}">
                            <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">环太平洋<a href="{{url_for('home.play')}}" class="label label-primary pull-right"><span
                                class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                        该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
                    </div>
                </div>
                {%endfor%}
            </div>
            <div class="col-md-12 text-center" style="margin-top:6px;">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block js%}
<script>
    $(document).ready(function () {
        $("#md5").addClass("active");
    });
</script>
{% endblock %}

movie-project/app/templates/home/search.html
{% extends "home/home.html" %}
{% block css %}
<script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
{% endblock%}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb" style="margin-top:6px;">
            <li>与"xxx"有关的电影，共x部</li>
        </ol>
    </div>
    <div class="col-md-12">
      {% for v in range(1,13) %}
        <div class="media">
            <div class="media-left">
                <a href="{{url_for('home.play')}}">
                    <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">环太平洋<a href="{{url_for('home.play')}}" class="label label-primary pull-right"><span
                        class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
            </div>
        </div>
    {%endfor%}
    </div>
    <div class="col-md-12 text-center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="First">
                        <span aria-hidden="true">首页</span>
                    </a>
                </li>
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">上一页</span>
                    </a>
                </li>
                <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">下一页</span>
                    </a>
                </li>
                <li>
                    <a href="#" aria-label="Last">
                        <span aria-hidden="true">尾页</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}